### ISSUE TITLE
按照文档运行没有任何日志，运行失败

### ISSUE THREAD

**Issue by ChinaArJun** [jkstack/natpass#16]
在同一台机器上运行了服务端和控制端
[root@VM-8-5-centos natpass-server]# sudo systemctl start np-svr
[root@VM-8-5-centos natpass-server]# sudo systemctl start np-cli
启动后没有任何提示，也没有日志输出，打开对应端口也是失败的

**Comment by lwch** [comment]
可能是因为没有权限创建logs目录，可尝试手工创建logs目录并将目录的权限设置为注册服务时指定的用户，稍后我会更新一下文档

**Comment by lwch** [comment]
在v0.7.3版本中已加入install时的自动创建log目录并设置属主的功能，请及时更新。
