### ISSUE TITLE
部署完成后怎么使用呢？

### ISSUE THREAD

**Issue by Wall-ee** [jkstack/natpass#17]
请问一下，部署完成后，怎么使用呢？打开url还是用什么终端？

**Comment by lwch** [comment]
请在浏览器中访问配置文件中的dashboard端口，如http://127.0.0.1:8080

**Comment by Wall-ee** [comment]
> 请在浏览器中访问配置文件中的dashboard端口，如http://127.0.0.1:8080

是那个rule.d文件里面配置的嘛？  Shell. Yaml？  里面？

**Comment by lwch** [comment]
> > 请在浏览器中访问配置文件中的dashboard端口，如http://127.0.0.1:8080
> 
> 是那个rule.d文件里面配置的嘛？ Shell. Yaml？ 里面？

主配置文件client.yaml
