### ISSUE TITLE
并发能力如何？

### ISSUE THREAD

**Issue by Leo-zhanglj** [jkstack/natpass#19]
请问一下，设计并发能力和测试并发能力如何？有大概的数据吗？

**Comment by lwch** [comment]
支持tcp层面的多路复用，公司的另外一个项目也是这种RPC模式，在4C8G的服务器上可以跑到7k+的qps。目前只保留了vnc和shell功能，应该没有什么性能方面的要求吧。

**Comment by lwch** [comment]
![image](https://user-images.githubusercontent.com/4181963/149742653-d3ead37d-4a8c-4371-9c2b-0544186e7576.png)

刚刚写了一个专门做benchmark的接口，从发起连接到等到连接返回，在4C2G的虚拟机里做了all in one的测试，大约能跑到8300+的qps，并且p99在30ms

**Comment by lwch** [comment]
另外发现增加虚拟连接数量反而会降低qps，可能是因为在做连接分配时的锁导致的，因此下版本中将会去除连接池的支持。

**Comment by lwch** [comment]
v0.8.2版本已去除连接池功能，在4C2G的机器上已达到了上万+的qps，详见README
